### ISSUE TITLE
build project structure

### ISSUE THREAD

**Issue by thdefn** [GilDongMu/gildongmu-server#1]
## 📌 Feature Issue
> build project structure

## 📝 To-do
- [x] create a multi-module based project structure
- [x] add components for handling exception
- [x] divide environment between develop and local
## ETC
>
