### ISSUE TITLE
build a segregated chat server

### ISSUE THREAD

**Issue by thdefn** [GilDongMu/gildongmu-server#18]
## 📌 Feature Issue
> build a segregated chat server

## 📝 To-do
- [x] build a chat server
- [x] set up for using mongoDB
- [x] set up basic architecture

## ETC
>
