### ISSUE TITLE
set up CD pipeline for the develop server

### ISSUE THREAD

**Issue by thdefn** [GilDongMu/gildongmu-server#3]
## 📌 Feature Issue
> set up continuous Delivery pipeline for the develop server

## 📝 To-do
- [x] create a docker hub account
- [x] set up docker environment on develop server
- [x] add IAM role with the ability to edit EC2 security groups
- [x] write a CD script

## ETC
>
