### ISSUE TITLE
add feature related to participation in trip post

### ISSUE THREAD

**Issue by thdefn** [GilDongMu/gildongmu-server#35]
## 📌 Feature Issue
> add feature related to participation in trip post

## 📝 To-do
- [x] add feature to accept apply for participant in trip post
- [x] add feature to deny apply for participant in trip post
- [x] add feature to apply for participant in trip post
- [x] add feature to exit or cancel participation in trip
## ETC
>
