### ISSUE TITLE
change api spec by request of front-end

### ISSUE THREAD

**Issue by Rekite** [GilDongMu/gildongmu-server#41]
## 📌 Feature Issue
> change api spec by request of front-end

## 📝 To-do
- [x] modify post tripdate api list to only json format
- [x] modify gender code from korean to english
- [x] modify everyone to view post lists

## ETC
>
