### ISSUE TITLE
fix latest-trip sort and delete feature bugs

### ISSUE THREAD

**Issue by Rekite** [GilDongMu/gildongmu-server#51]
## 📌 Feature Issue
> fix post feature bugs

## 📝 To-do
- [ ] fix latest-trip sorts
- [ ] fix whole sorts
- [x] fix delete post feature bugs
- [x] image null

## ETC
>
