### ISSUE TITLE
chat feature enhancement

### ISSUE THREAD

**Issue by thdefn** [GilDongMu/gildongmu-server#67]
## 📌 Feature Issue
> implement of detailed requirements for chat

## 📝 To-do
- [ ] add room-related validation when the user chats
- [ ] sorting chat list by date during retrieval
- [ ] implementation of bookmark feature for chat list retrieval

## ETC
>
